timeout: 3

/Kyuzen OS
    protocol: multiboot1
    kernel_path: boot():/myos.bin

    module_path: boot():/logo.png
    module_string: logo.png

    module_path: boot():/fileman.elf
    module_string: fileman.elf

    module_path: boot():/viewer.elf
    module_string: viewer.elf